[package]
name = "calculating_pi_rust"
version = "0.0.2"
edition = "2021"


[dependencies]
num_cpus = "1.13.1"
sysinfo = "0.26.2"
log = "0.4.17"
rug = "1.17.0"
flate2 = "1.0"
tar = "0.4"
hyper = "0.14.20"

[dev-dependencies]
criterion = "0.4.0"


[[bench]]
name = "calculating_pi"
harness = false
